customers:
  message: "Bem-vindo! Somos a API Rest, Micro_Customers no ambiente de Desenvolvimento."
  contactDetails:
    name: "Junior Martins - Developer"
    email: "teste@teste.com"
  onCallSupport:
    - (11) 9999-2222
    - (21) 3333-5555

