customers:
  message: "Bem-vindo! Somos a API Rest, Micro_Customers no ambiente de Produção - Classpath."
  contactDetails:
    name: "Martin Fowler - Product Owner"
    email: "fowler@teste.com"
  onCallSupport:
    - (11) 9999-0000
    - (21) 3333-8888

