contacts:
  message: "Bem-vindo! Somos a API Rest, Micro_Empresas no ambiente de QA - Classpath."
  contactDetails:
    name: "Kent Beck - QA Lead"
    email: "beck@teste.com"
  onCallSupport:
    - (11) 9999-1111
    - (21) 3333-6666


