customers:
  message: "Bem-vindo! Somos a API Rest, Micro_Customers no ambiente de QA."
  contactDetails:
    name: "Kent Beck - QA Lead"
    email: "{cipher}456c1793e37edc6890a52f5d5d122d7df3ee85d976cd60666d96c25fca7aa634"
  onCallSupport:
    - (11) 9999-1111
    - (21) 3333-6666

