build:
  version: "2.0.0"

customers:
  message: "Bem-vindo! Somos a API Rest, Micro_Customers no ambiente de QA."
  contactDetails:
    name: "Kent Beck - QA Lead"
    email: "beck@teste.com"
  onCallSupport:
    - (11) 9999-1111
    - (21) 3333-6666

