server:
  port: ${SERVER_PORT:9103}

spring:

  application:
    name: micro_emails

  profiles:
    active:
      - "prod"
  config:
#    import: "optional:configserver:http://localhost:9201/"
    import: "optional:configserver:http://${CONFIG_SERVER:localhost}:${CONFIG_SERVER_PORT:9201}/"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: prometheus,auditevents,beans,caches,conditions,configprops,env,flyway,health,httpexchanges,info,integrationgraph,loggers,metrics,mappings,quartz,scheduledtasks,sessions,shutdown,startup,threaddump
    metrics:
      enabled: true
      tags:
        application: ${spring.application.name}
    prometheus:
      enabled: true

info:
  app: Microsserviços com Java e Spring Boot.
  website: https://babystepsdev.com
  github: https://github.com/juniorsmartins/microservices_mercado_financeiro


