version: "3.9"

services:

  micro_empresas_postgres16:
    container_name: micro_empresas_postgres16
    image: postgres:16.0
    restart: always
    networks:
      - mercado_financeiro_net
    environment:
      - POSTGRES_DB=micro_empresas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - micro-empresas-postgresql-data:/var/lib/postgresql/data

  micro_empresas:
    container_name: micro_empresas
    build:
      context: ./
      dockerfile: ./micro_empresas/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    restart: always
    networks:
      - mercado_financeiro_net
    env_file:
      - ./micro_empresas/.env
    depends_on:
      - micro_empresas_postgres16

  micro_emails:
    container_name: micro_emails
    build:
      context: ./
      dockerfile: ./micro_emails/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    restart: always
    networks:
      - mercado_financeiro_net
    env_file:
      - ./micro_emails/.env
  #    depends_on:
  #      - micro_emails_postgres16



  sonarqube_postgres16:
    container_name: sonarqube_postgres16
    image: postgres:16.0
    networks:
      - mercado_financeiro_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - sonarqube-postgresql:/var/lib/postgresql
      - sonarqube-postgresql-data:/var/lib/postgresql/data

  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9.4-community
    ports:
      - "9000:9000"
    networks:
      - mercado_financeiro_net
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube_postgres16:5432/sonar
    depends_on:
      - sonarqube_postgres16
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins


  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.440.2-lts-jdk21
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    #      - jenkins-docker:/usr/local/bin/docker
    networks:
      - mercado_financeiro_net



volumes:
  micro-empresas-postgresql-data:
    name: micro-empresas-postgresql-data

  sonarqube-postgresql:
    name: sonarqube-postgresql
  sonarqube-postgresql-data:
    name: sonarqube-postgresql-data

  sonarqube_conf:
    name: sonarqube_conf
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  sonarqube_bundled-plugins:
    name: sonarqube_bundled-plugins

  jenkins-home:
    name: jenkins-home
#  jenkins-docker:
#    name: jenkins-docker


networks:
  mercado_financeiro_net:
    name: mercado_financeiro_net
    driver: bridge

