version: "3.9"

services:

  micro_empresas_postgres16:
    container_name: micro_empresas_postgres16
    image: postgres:16.0
    restart: always
    networks:
      - mercado_financeiro_net
    environment:
      - POSTGRES_DB=micro_empresas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql/data

  micro_empresas:
    container_name: micro_empresas
    build:
      context: ./
      dockerfile: ./micro_empresas/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    restart: always
    networks:
      - mercado_financeiro_net
    env_file:
      - ./micro_empresas/.env
    depends_on:
      - micro_empresas_postgres16




  jenkins:
    container_name: jenkins
#    image: jenkins/jenkins:lts-jdk21
    image: jenkins/jenkins:2.60.3
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#      - jenkins-docker:/usr/local/bin/docker
    networks:
      - mercado_financeiro_net


volumes:
  data-postgresql:
    name: data-postgresql

  jenkins-home:
    name: jenkins-home
#  jenkins-docker:
#    name: jenkins-docker


networks:
  mercado_financeiro_net:
    name: mercado_financeiro_net
    driver: bridge

