global:
  scrape_interval: 45s
  scrape_timeout: 30s
  evaluation_interval: 20s

alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090

  - job_name: micro_empresas
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - micro_empresas:8081

#  - job_name: micro_emails
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    static_configs:
#      - targets:
#        - micro_emails:8082


