global:
  scrape_interval: 45s
  scrape_timeout: 30s
  evaluation_interval: 20s

scrape_configs:
  - job_name: prometheus
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: micro_empresas
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.1.24:8081"]

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: []
#      scheme: http
#      timeout: 10s
