server:
  port: ${SERVER_PORT:8093}

spring:

  application:
    name: micro_customers

  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:micro_customers}?serverTimezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    sql-script-encoding: UTF-8
    characterEncoding: UTF-8
    hikari:
      pool-name: poll_micro_customers
      maxLifetime: 1800000
      connection-timeout: 40000
      idle-timeout: 300000
      maximum-pool-size: 2

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        type:
          enumType:
            type: pgsql_enum
        jdbc:
          log:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true

build:
  version: "3.0"

customers:
  message: "Bem-vindo! Somos a API Rest, Micro_Customers no ambiente de Desenvolvimento."
  contactDetails:
    name: "Junior Martins - Developer"
    email: "teste@teste.com"
  onCallSupport:
    - (11) 9999-2222
    - (21) 3333-5555

