spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

customers:
  message: "Bem-vindo! Somos a API Rest, Micro_Customers no ambiente de QA."
  contactDetails:
    name: "Kent Beck - QA Lead"
    email: "beck@teste.com"
  onCallSupport:
    - (11) 9999-2222
    - (21) 3333-5555

