spring:
  config:
    activate:
      on-profile: "dev"

contacts:
  message: "Bem-vindo! Somos a API Rest, Micro_Empresas no ambiente de Desenvolvimento."
  contactDetails:
    name: "Junior Martins - Developer"
    email: "teste@teste.com"
  onCallSupport:
    - (11) 9999-2222
    - (21) 3333-5555


