server:
  port: ${SERVER_PORT:18091}

spring:

  application:
    name: micro_empresas

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:micro_empresas}?serverTimezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    sql-script-encoding: UTF-8
    characterEncoding: UTF-8
    hikari:
      pool-name: poll_micro_empresas
      maxLifetime: 1800000
      connection-timeout: 40000
      idle-timeout: 300000
      maximum-pool-size: 2

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        type:
          enumType:
            type: pgsql_enum
        jdbc:
          log:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true



management:
  endpoints:
    web:
      exposure:
        include: prometheus,auditevents,beans,caches,conditions,configprops,env,flyway,health,httpexchanges,info,integrationgraph,loggers,metrics,mappings,quartz,scheduledtasks,sessions,shutdown,startup,threaddump
    metrics:
      enabled: true
      tags:
        application: ${spring.application.name}
    prometheus:
      enabled: true

info:
  app: Microsserviços com Java e Spring Boot.
  website: https://babystepsdev.com
  github: https://github.com/juniorsmartins/microservices_mercado_financeiro


