server:
  port: 8888

spring:

  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/juniorsmartins/configserver.git"
#          username: username-de-repositório-privado
#          password: password-de-repositório-privado
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths:
            - 'eurekaserver*'
            - 'gatewayserver*'
            - 'microcustomers*'
            - 'microempresas*'
            - 'microemails*'

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "6z$63r@=;(}.f^]u|j/*@l}.0`|8y!fwm%j~0,q#+e[og{hk3s8w~.?[:i}e$pw"

