server:
  port: 8888

spring:

  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/juniorsmartins/configserver.git"
#          username: username-de-repositório-privado
#          password: password-de-repositório-privado
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths:
            - 'eurekaserver*'
            - 'gatewayserver*'
            - 'microcustomers*'
            - 'microempresas*'
            - 'microemails*'

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

#management:
#  endpoints: # Essa seção define a configuração geral dos endpoints de gerenciamento.
#    web: # Configura o endpoint web de gerenciamento.
#      exposure: # Especifica quais endpoints serão expostos através do endpoint web.
#        include: "*" # Configura quais endpoints de gerenciamento da aplicação devem estar expostos. O asterisco "*" diz para expor todos.
#  health:
#    readiness-state:
#      enabled: true # Habilita o estado de prontidão (readiness state) para a verificação de saúde da aplicação. Indica se a aplicação está pronta para receber tráfego.
#    liveness-state:
#      enabled: true # Habilita o estado de vivacidade (liveness state) para a verificação de saúde da aplicação. Indica se a aplicação está viva e funcionando corretamente.
#  endpoint:
#    health:
#      show-details: always # Configura o nível de detalhe das informações mostradas pelo endpoint de saúde (/actuator/health). O valor 'always' exibe todos os detalhes sobre o estado de saúde da aplicação, independentemente de quem está solicitando a informação (seja usuário autenticado ou não).
#      probes:
#        enabled: true # Habilita a inclusão de probes (sondas) de readiness e liveness nas respostas do endpoint de saúde (/actuator/health). São verificações adicionais que indicam o estado de readiness e liveness diretamente no endpoint de saúde.

encrypt:
  key: "6z$63r@=;(}.f^]u|j/*@l}.0`|8y!fwm%j~0,q#+e[og{hk3s8w~.?[:i}e$pw"

