services:

  network-deploy-service:
    networks:
      - mercado_financeiro_net

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:9201/

