services:

  microservice-resources-config:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  microservice-eureka-config:
    extends:
      service: microservice-resources-config
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  microservice-config:
    extends:
      service: microservice-eureka-config
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  microservice-postgres16-config:
    extends:
      service: microservice-resources-config
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      timeout: 10s # Tempo limite de espera antes de assumir como falha
      retries: 10 # Quantidade de tentativas
      interval: 10s # Intervalo entre tentativas
      start_period: 10s # Tempo de delay antes de começar a checagem

  microservice-mysql8-config:
    extends:
      service: microservice-resources-config
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s # Tempo limite de espera antes de assumir como falha
      retries: 10 # Quantidade de tentativas
      interval: 10s # Intervalo entre tentativas
      start_period: 10s # Tempo de delay antes de começar a checagem


