services:

  microservice-resources-config:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  microservice-postgres16-config:
    extends:
      service: microservice-resources-config
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      timeout: 10s # Tempo limite de espera antes de assumir como falha
      retries: 10 # Quantidade de tentativas
      interval: 10s # Intervalo entre tentativas
      start_period: 10s # Tempo de delay antes de começar a checagem

  microservice-mysql8-config:
    extends:
      service: microservice-resources-config
    image: mysql:8.0.17
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s # Tempo limite de espera antes de assumir como falha
      retries: 10 # Quantidade de tentativas
      interval: 10s # Intervalo entre tentativas
      start_period: 10s # Tempo de delay antes de começar a checagem


