services:

  microservice-resources-config:
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 412M

  microservice-postgres16-config:
    extends:
      service: microservice-resources-config
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      timeout: 30s # Tempo limite de espera antes de assumir como falha
      interval: 30s # Intervalo entre tentativas
      retries: 3 # Quantidade de tentativas
      start_period: 30s # Tempo de delay antes de começar a checagem

  microservice-mysql8-config:
    extends:
      service: microservice-resources-config
    image: mysql:8.0.29
    environment:
      TZ: UTC
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s # Tempo limite de espera antes de assumir como falha
      interval: 30s # Intervalo entre tentativas
      retries: 3 # Quantidade de tentativas
      start_period: 30s # Tempo de delay antes de começar a checagem


